baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'isjaya'
theme = 'hello-friend-ng'
paginate     = 10
rssLimit = 10

[author]
  name = "Isjaya"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "+++++ +++++ [->++ +++++ +++<] >++++ +++++ +++++ +.--- ----- .--.+ ++..<+++++ +++[- >---- ----< ]>--- ----- ----. <++++ ++++[ ->+++ +++++ <]>+++++++ ++.<+ ++[-> +++<] >+..+ +.<++ ++[-> ----< ]>.<"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [params.footer]
    trademark = true
    rss = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello-friend-ng</a> theme by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"]
  
  [params.portrait]
    path     = "/images/pfp.jpg"
    alt      = "Portrait"
    maxWidth = "200px"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ishxd"

  [[params.social]]
    name = "tryhackme"
    url  = "https://tryhackme.com/p/ishajayal1"

  [[params.social]]
    name = "hackthebox"
    url  = "https://app.hackthebox.com/profile/1573255"

[taxonomies]
    category = "category"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Isjaya"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/isjaya"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "./posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "./about"
    url        = "/about"

